# Generated by Django 3.2.4 on 2021-06-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0002_grettings_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='grettings',
            name='temp',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
