# Generated by Django 3.2.4 on 2021-06-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0003_grettings_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grettings',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='grettings',
            name='temp',
        ),
    ]
