# Generated by Django 3.2.4 on 2021-06-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='init_point',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
